python main.py --gpus "0," --max_epochs=20  --num_workers=32 \
   --model_name_or_path  facebook/bart-base \
   --accumulate_grad_batches 1 \
   --model_class BartKGC \
   --batch_size 128 \
   --check_val_every_n_epoch 10 \
   --limit_val_batches 0.1 \
   --data_dir dataset/umls \
   --overwrite_cache \
   --preseqlen 10 \
   --output_full_sentence 1 \
   --prefix_tree_decode 1 \
   --max_seq_length 64 \
   --lr 5e-5