python main.py --gpus "1," --max_epochs=30  --num_workers=16 \
   --model_name_or_path  facebook/bart-base \
   --accumulate_grad_batches 1 \
   --model_class BartKGC \
   --batch_size 16 \
   --check_val_every_n_epoch 5 \
   --data_dir dataset/umls \
   --overwrite_cache \
   --wandb \
   --output_full_sentence 0 \
   --prefix_tree_decode 1 \
   --max_seq_length 128 \
   --precision 16 \
   --lr 3e-5 